'use client'
import { useEffect } from 'react';
import { segoe } from '@/app/fonts';
import Provider from "@/components/ui/Provider/index";
import AOS from 'aos';
import 'aos/dist/aos.css';
import "../globals.css";
import styles from "./style.module.scss";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  useEffect(() => {
    AOS.init({
      once: true,
      disable: 'phone',
      duration: 600,
      easing: 'ease-out-sine',
    })
  },)

  return (
    <html >
      <body className={`${segoe.variable} ${styles.layout_body} `} >
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
