'use client'
import { segoe } from '@/app/fonts';
import Provider from "@/components/ui/Provider/index";
import "../globals.css";
import styles from "./style.module.scss";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html >
      <body className={`${segoe.variable} ${styles.layout_body} `} >
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
