import { segoe } from '@/app/fonts';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AdminLayout({ children }) {
  return (
    <html lang="en">
      <body className={segoe.className}>
        {children}
      </body>
    </html>
  );
}
