'use client'
import { useEffect } from 'react';
import { segoe } from '@/app/fonts';
import { PrimeReactProvider } from 'primereact/api';
import Provider from "@/components/layout/provider";
import AOS from 'aos';
import 'aos/dist/aos.css';
import "primereact/resources/themes/saga-blue/theme.css";
import 'primeicons/primeicons.css';
import "../globals.css";


// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  useEffect(() => {
    AOS.init({
      duration: 800,
      once: false,
    });
  }, []);

  return (
    <PrimeReactProvider>
      <html >
        <body className={`${segoe.variable} h-full antialiased `} >
          <Provider>
            <main className="flex flex-col items-center justify-between w-full min-h-screen">
              {children}
            </main>
          </Provider>
        </body>
      </html>
    </PrimeReactProvider >
  );
}
