'use client'
import { useEffect } from 'react';
import { Inter } from "next/font/google";
import NavbarComp from "@/components/LayoutComp/LayoutMenu/NavbarComp";
import { PrimeReactProvider } from 'primereact/api';
import Provider from "@/components/provider";
import AOS from 'aos';
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import 'aos/dist/aos.css';
import "primereact/resources/themes/saga-blue/theme.css";
import 'primeicons/primeicons.css';
import "../globals.css";


const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  useEffect(() => {
    AOS.init({
      duration: 800,
      once: false,
    });
  }, []);

  return (
    <PrimeReactProvider>
      <html >
        <body className={`${inter.className} h-full`} >
          <Provider>
            <main className="flex flex-col items-center justify-between w-full min-h-screen">
              <div className="w-full min-h-full">
                <NavbarComp multi />
                <div className="mx-auto z-10 mt-0 ">
                  {children}
                </div>
              </div>
            </main>
          </Provider>
        </body>
      </html>
    </PrimeReactProvider>
  );
}
